---
- name: Get Kafka Cluster Id
  import_role:
    name: common
    tasks_from: rbac_setup.yml
  vars:
    copy_certs: false

- name: Register Kafka Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/registry/clusters"
    method: POST
    validate_certs: false
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ authorization_token }}"
    body_format: json
    # For audit logs, must register the oauth listener which will be the "internal" listener
    body: >
      [
          {
              "clusterName": "{{kafka_broker_cluster_name}}",
              "scope": {
                  "clusters": {
                      "kafka-cluster": "{{kafka_cluster_id}}"
                  }
              },
              "hosts": [ {% for host in groups['kafka_broker'] %}{% if loop.index > 1%},{% endif %}{ "host": "{{host}}", "port": {{kafka_broker_listeners.internal.port}} }{% endfor %}
              ],
              "protocol": "{{kafka_broker_listeners.internal.sasl_protocol|default(sasl_protocol) | confluent.platform.kafka_protocol(kafka_broker_listeners.internal.ssl_enabled|default(ssl_enabled)) }}"
          }
      ]
    status_code: 204
  run_once: true
  no_log: "{{mask_secrets|bool}}"
  register: output
  until: output.status == 204
  retries: "{{ mds_retries }}"
  delay: 10
