- name: Run connection test (telnet)
  shell: curl -v --connect-timeout 3 {{ ansible_host }}:{{ telnet_port }} 2>&1
  register: curl_output
  ignore_errors: true
  tags: telnet

- name: Check if the connection was successful
  debug:
    msg: "Connection to {{ ansible_host }} on port {{ telnet_port }} was successful!"
  when: "'Connected' in curl_output.stdout"
  tags: telnet

- name: Check Kafka process uptime
  shell: |
    ps -eo pid,etime,cmd | grep -v grep | grep kafka.Kafka | awk '{print $2}'
  register: kafka_uptime
  ignore_errors: true
  tags: kafka_uptime

- name: Display Kafka process uptime
  debug:
    msg: "Kafka process uptime: {{ kafka_uptime.stdout }}"
  when: kafka_uptime.stdout != ""
  tags: kafka_uptime

- name: Get active controller node
  shell: curl {{ ansible_host }}:{{ kafka_jmx_metric_port }}/metrics | grep activecontrollercount | grep -v '^#' | awk '{print $2}'
  register: active_controller_node
  ignore_errors: true
  tags: jmx_metrics

- name: Display active controller node
  debug:
    msg: "Active controller node: {{ active_controller_node.stdout }}"
  when: active_controller_node.stdout != ""
  tags: jmx_metrics