---
- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: "{{kafka_controller_service_name}}"
    state: restarted
  tags:
    - systemd
  when: not nonroot_deployment

- name: Stop Kafka Controller (Shell Script)
  ansible.builtin.shell: "{{ start_script_path }}/kafka_controller_stop.sh"
  when: nonroot_deployment
  ignore_errors: true

- name: Wait for Kafka Controller to Stop
  wait_for:
    timeout: 10
  when: nonroot_deployment

- name: Start Kafka Controller (Shell Script)
  ansible.builtin.shell: "{{ start_script_path }}/kafka_controller_start.sh"
  when: nonroot_deployment

- name: Wait for Kafka Controller to Start
  wait_for:
    timeout: 10