---
- name: Kafka Connect Status Finding
  hosts: kafka_connect
  gather_facts: false
  tags: kafka_connect
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: variables

    - name: Populate service facts
      service_facts:
      when: not nonroot_deployment

    # Check for Kafka Connect process regardless of systemd or custom script
    - name: Check if Kafka Connect process is running
      ansible.builtin.shell: |
        ps aux | grep -w 'ConnectDistributed' | grep -v 'grep' || true
      register: kafka_process_check
      ignore_errors: true
      when: nonroot_deployment

    # Set service state based on process check
    - name: Set Kafka Connect service state based on process detection
      set_fact:
        ansible_facts:
          services: "{{ ansible_facts.services | default({}) | combine({ (kafka_connect_service_name + '.service'): { 'state': 'running' if kafka_process_check.stdout else 'stopped' } }) }}"
      when: nonroot_deployment

    - name: Show Kafka Connect service state based on process detection
      debug:
        msg: "State: {{ ansible_facts.services}}"

    - name: Determine Installation Pattern - Parallel or Serial
      set_fact:
        install_pattern: "{{ 'parallel' if service_state != 'running' or kafka_connect_deployment_strategy == 'parallel' else 'serial' }}"
      vars:
        service_state: "{{ ansible_facts.services[kafka_connect_service_name + '.service'].state | default('unknown') }}"

    - name: Group Hosts by Installation Pattern
      group_by:
        key: kafka_connect_{{install_pattern}}
      changed_when: false

- name: Kafka Connect Parallel Provisioning
  hosts: kafka_connect_parallel
  gather_facts: false
  tags: kafka_connect
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_connect

- name: Kafka Connect Serial Provisioning
  hosts: kafka_connect_serial
  serial: 1
  any_errors_fatal: true
  gather_facts: false
  tags: kafka_connect
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_connect

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: kafka_connect_pause_rolling_deployment|bool
