---
- name: Kafka Broker Status Finding
  hosts: kafka_broker
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: variables

    - name: Populate service facts
      service_facts:
      when: not nonroot_deployment

    # Check for Kafka process regardless of systemd or custom script
    - name: Check if Kafka process is running
      ansible.builtin.shell: |
        ps aux | grep -w '[k]afka.Kafka' || true
      register: kafka_process_check
      ignore_errors: true
      when: nonroot_deployment

    # Set service state based on process check
    - name: Set Kafka service state based on process detection
      set_fact:
        ansible_facts:
          services:
            "{{ kafka_broker_service_name + '.service' }}":
              state: "{{ 'running' if kafka_process_check.stdout else 'stopped' }}"
      when: nonroot_deployment

    - name: Show Kafka service state based on process detection
      debug:
        msg: "State: {{ kafka_broker_service_name + '.service' }}: {{ ansible_facts.services[kafka_broker_service_name + '.service'].state"

    - name: Determine Installation Pattern - Parallel or Serial
      set_fact:
        install_pattern: "{{ 'parallel' if service_state != 'running' or kafka_broker_deployment_strategy == 'parallel' else 'serial' }}"
      vars:
        service_state: "{{ ansible_facts.services[kafka_broker_service_name + '.service'].state | default('unknown') }}"

    - name: Group Hosts by Installation Pattern
      group_by:
        key: kafka_broker_{{install_pattern}}
      changed_when: false

- name: Kafka Broker Parallel Provisioning
  hosts: kafka_broker_parallel
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_broker

# The motivation for rolling the "active controller" last doesn't apply to KRaft because failover (i.e. election of a new leader/active controller) is very fast
- name: Kafka Broker Serial Provisioning
  hosts: kafka_broker_serial
  gather_facts: false
  serial: 1
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_broker
      when: kraft_enabled|bool

- name: Kafka Broker Serial Ordering
  hosts: kafka_broker_serial
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_broker
        tasks_from: dynamic_groups.yml
      when: not kraft_enabled|bool

- name: Kafka Broker Non Controllers Provisioning
  hosts: kafka_broker_non_controller
  serial: 1
  any_errors_fatal: true
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_broker

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: kafka_broker_pause_rolling_deployment|bool

- name: Kafka Broker Controller Provisioning
  hosts: kafka_broker_controller
  any_errors_fatal: true
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: kafka_broker

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: kafka_broker_pause_rolling_deployment|bool
