---
- name: Zookeeper Status Finding
  hosts: zookeeper
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: variables

    - name: Populate service facts
      service_facts:
      when: not nonroot_deployment

    # Check for Zookeeper process regardless of systemd or custom script
    - name: Check if Zookeeper process is running
      ansible.builtin.shell: |
        ps aux | grep -w 'zookeeper.server' | grep -v "grep" || true
      register: kafka_process_check
      ignore_errors: true
      when: nonroot_deployment

    # Set service state based on process check
    - name: Set Zookeeper service state based on process detection
      set_fact:
        ansible_facts:
          services: "{{ ansible_facts.services | default({}) | combine({ (zookeeper_service_name + '.service'): { 'state': 'running' if kafka_process_check.stdout else 'stopped' } }) }}"
      when: nonroot_deployment

    - name: Show Zookeeper service state based on process detection
      debug:
        msg: "State: {{ ansible_facts.services}}"

    - name: Determine Installation Pattern - Parallel or Serial
      set_fact:
        install_pattern: "{{ 'parallel' if service_state != 'running' or zookeeper_deployment_strategy == 'parallel' else 'serial' }}"
      vars:
        service_state: "{{ ansible_facts.services[zookeeper_service_name + '.service'].state | default('unknown') }}"

    - name: Group Hosts by Installation Pattern
      group_by:
        key: zookeeper_{{install_pattern}}
      changed_when: false

- name: Zookeeper Parallel Provisioning
  hosts: zookeeper_parallel
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper

- name: Zookeeper Serial Ordering
  hosts: zookeeper_serial
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper
        tasks_from: dynamic_groups.yml

- name: Zookeeper Followers Provisioning
  hosts: zookeeper_follower
  serial: 1
  any_errors_fatal: true
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: zookeeper_pause_rolling_deployment|bool

- name: Zookeeper Leader Provisioning
  hosts: zookeeper_leader
  any_errors_fatal: true
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: zookeeper_pause_rolling_deployment|bool
